name: Java CI pipeline
on:
  push:
    branches: [ "Dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - name: Upload Artifact
        if: success()  # Only execute if previous steps were successful
        uses: actions/upload-artifact@v3
        with:
          name: nest-navigate
          path: "/nestNavigate.war"